import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const suiteSans = localFont({
  src: "./fonts/SUITE-Variable.woff2",
  // variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${suiteSans} antialiased`}>{children}</body>
    </html>
  );
}
